{{- range $name, $attrs := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "es-secrets.labels" $ | nindent 4 }}
    {{- with $attrs.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $attrs.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $attrs.clusterSecretStoreName }}
  refreshInterval: {{ $attrs.refreshInterval | default "1h" | quote }}
  {{- with $attrs.target }}
  target:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $attrs.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $attrs.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
