---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.acme.server }}
    email: {{ .Values.clusterIssuer.acme.email }}
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.clusterIssuer.acme.cloudflare.email }}
          apiTokenSecretRef:
            name: cert-manager-cloudflare
            key: api-token
