---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.azkv.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    azurekv:
      tenantId: 9aec5953-18f3-48be-9df6-d756ae4acf82
      vaultUrl: {{ .Values.azkv.url }}
      authSecretRef:
        clientId:
          name: {{ .Values.azkv.sp.clientId }}
          key: ClientID
          namespace: {{ .Release.Namespace }}
        clientSecret:
          name: {{ .Values.azkv.sp.clientSecret }}
          key: ClientSecret
          namespace: {{ .Release.Namespace }}
